/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.roy.kafkags.schemas;
@org.apache.avro.specific.AvroGenerated
public enum EventType implements org.apache.avro.generic.GenericEnumSymbol<EventType> {
  CLICK, HOVER, BACK, FORWARD, SCROLL, KEY_PRESS, MOVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"org.roy.kafkags.schemas\",\"symbols\":[\"CLICK\",\"HOVER\",\"BACK\",\"FORWARD\",\"SCROLL\",\"KEY_PRESS\",\"MOVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
